<?php

namespace Database\Seeders;

use App\Models\Position;
use Illuminate\Database\Seeder;

class   MembersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('members')->delete();

        \DB::table('members')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Randy Rosenbaum Jr.',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 1,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-09-27',
                'end_date' => '2024-03-27',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Hobart Borer',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 1,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-02-12',
                'end_date' => '2023-08-12',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Mr. Myles Lang III',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 1,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2024-03-19',
                'end_date' => '2024-09-19',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Austyn Wilderman',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 1,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-01-29',
                'end_date' => '2023-07-29',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Gage White I',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 1,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-03-18',
                'end_date' => '2023-09-18',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Hillard Zulauf',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 1,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-05-12',
                'end_date' => '2023-11-12',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Mr. Kane Schroeder',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 2,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-11-18',
                'end_date' => '2024-05-18',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Lucile Gutmann',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 2,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2024-03-25',
                'end_date' => '2024-09-25',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Dr. Julius Sporer',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 2,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-07-04',
                'end_date' => '2024-01-04',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Brenden Mante Jr.',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 2,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-12-05',
                'end_date' => '2024-06-05',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Kris Daniel',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 2,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2024-03-18',
                'end_date' => '2024-09-18',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Miss Celine Weissnat',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 2,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-10-29',
                'end_date' => '2024-04-29',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Mr. Sven Bernhard DDS',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 3,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-08-13',
                'end_date' => '2024-02-13',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Albin Hahn',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 3,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-07-07',
                'end_date' => '2024-01-07',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Alisha Friesen',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 3,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-07-17',
                'end_date' => '2024-01-17',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Toy Beier I',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 3,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-11-05',
                'end_date' => '2024-05-05',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'Prof. Norwood Feest Jr.',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 3,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2024-02-18',
                'end_date' => '2024-08-18',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'Miss Avis Willms',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 3,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2024-03-21',
                'end_date' => '2024-09-21',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'Ms. Scarlett Lynch',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 4,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2024-02-17',
                'end_date' => '2024-08-17',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'Rosina McKenzie PhD',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 4,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2024-03-19',
                'end_date' => '2024-09-19',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'Jan Shields',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 4,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2024-03-03',
                'end_date' => '2024-09-03',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'Godfrey McLaughlin PhD',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 4,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-08-31',
                'end_date' => '2024-03-02',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'Sonia Murray',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 4,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-04-11',
                'end_date' => '2023-10-11',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'Ashlee Schmitt',
                'type' => 4,
                'committable_type' => 'Committee',
                'committable_id' => 4,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-01-21',
                'end_date' => '2023-07-21',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:49',
                'updated_at' => '2024-04-22 11:22:49',
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'Gabrielle Daniel',
                'type' => 1,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-02-06',
                'end_date' => '2023-08-06',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'Mrs. Kira Abbott PhD',
                'type' => 1,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-03-16',
                'end_date' => '2023-09-16',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'Dr. Shanel Schimmel Jr.',
                'type' => 1,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-06-04',
                'end_date' => '2023-12-04',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'Hudson Bahringer',
                'type' => 1,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2024-01-15',
                'end_date' => '2024-07-15',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'Chelsea Beatty',
                'type' => 1,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-12-18',
                'end_date' => '2024-06-18',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'Myrtle Block DDS',
                'type' => 1,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-11-05',
                'end_date' => '2024-05-05',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'Keaton Buckridge',
                'type' => 2,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-11-17',
                'end_date' => '2024-05-17',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            31 =>
            array (
                'id' => 32,
                'name' => 'Gardner Stroman',
                'type' => 2,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2024-01-13',
                'end_date' => '2024-07-13',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            32 =>
            array (
                'id' => 33,
                'name' => 'Clementina Wuckert',
                'type' => 2,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-04-08',
                'end_date' => '2023-10-08',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            33 =>
            array (
                'id' => 34,
                'name' => 'Alexandria Crooks',
                'type' => 2,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-05-21',
                'end_date' => '2023-11-21',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            34 =>
            array (
                'id' => 35,
                'name' => 'Eldon Bode V',
                'type' => 2,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-11-19',
                'end_date' => '2024-05-19',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            35 =>
            array (
                'id' => 36,
                'name' => 'Sadye Mills',
                'type' => 2,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-04-18',
                'end_date' => '2023-10-18',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            36 =>
            array (
                'id' => 37,
                'name' => 'Ms. Sasha Ondricka Jr.',
                'type' => 3,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>Position::all()->random()->id,
                'start_date' => '2023-05-24',
                'end_date' => '2023-11-24',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            37 =>
            array (
                'id' => 38,
                'name' => 'Shirley Hilpert',
                'type' => 3,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2023-04-30',
                'end_date' => '2023-10-30',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            38 =>
            array (
                'id' => 39,
                'name' => 'Antwan Abernathy',
                'type' => 3,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' =>  Position::all()->random()->id,
                'start_date' => '2024-03-11',
                'end_date' => '2024-09-11',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            39 =>
            array (
                'id' => 40,
                'name' => 'Deven Runolfsdottir',
                'type' => 3,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-01-11',
                'end_date' => '2023-07-11',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            40 =>
            array (
                'id' => 41,
                'name' => 'Dr. Tremaine Carroll V',
                'type' => 3,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-02-12',
                'end_date' => '2023-08-12',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
            41 =>
            array (
                'id' => 42,
                'name' => 'Lorenzo Wilkinson',
                'type' => 3,
                'committable_type' => NULL,
                'committable_id' => NULL,
                'position_id' => Position::all()->random()->id,
                'start_date' => '2023-04-14',
                'end_date' => '2023-10-14',
                'period'=> 6,
                'is_active' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-22 11:22:50',
                'updated_at' => '2024-04-22 11:22:50',
            ),
        ));


    }
}
