<?php

namespace Database\Seeders;

use App\Enums\UserGenderEnum;
use App\Enums\UserTypeEnum;
use App\Models\User;
use App\Repositories\Contracts\UserContract;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class NormalUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('users')->where('type', UserTypeEnum::user->value)->delete();
        \DB::table('users')->insert(array (
            1 =>
                array (
                    'id' => 2,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'user user',
                    'email' => 'user@gmail.com',
                    'phone' => '0100000000',
                    'password' =>  Hash::make('celiac@123'),
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => '1995-01-01',
                    'verified_at' => now(),
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-28 11:14:04',
                    'updated_at' => '2024-04-29 13:02:47',
                ),
            2 =>
                array (
                    'id' => 3,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'user',
                    'email' => 'user@user.com',
                    'phone' => '512345678',
                    'password' => '$2y$10$pWvdKFzXjU8CC4awIvAwk.B.b2k575y8WSKltpcbqHUCx6yWjTosS',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => '1995-01-01',
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-28 11:14:04',
                    'updated_at' => '2024-04-28 11:14:04',
                ),
            3 =>
                array (
                    'id' => 28,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'Madison Wagner',
                    'email' => 'Madison@gmail.com',
                    'phone' => '556677887',
                    'password' => '$2y$10$v9eaJdieWP5lwXUj7OTcRu/fbhUQMsf4guSv0DjvXCHz0TJsjSCmi',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => '1995-01-01',
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-28 13:07:50',
                    'updated_at' => '2024-04-28 13:07:50',
                ),
            4 =>
                array (
                    'id' => 29,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'Damian Brennan',
                    'email' => 'vilihylomi@mailinator.com',
                    'phone' => '555555555',
                    'password' => '$2y$10$Uq9fqcnmk.hnruPe25DJTesGJtCwuwbvh2wGohWwMrS.9kzquwv.y',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => '1995-01-01',
                    'verified_at' => '2024-04-28 13:11:49',
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-28 13:10:26',
                    'updated_at' => '2024-04-30 06:51:42',
                ),
            5 =>
                array (
                    'id' => 30,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test_admin055',
                    'email' => 'test_admin055@gmail.com',
                    'phone' => '578945612',
                    'password' => '$2y$10$5sxuNYxkmjz07MddnUKzEeiXIaOHUJ1muQKv49E3QA0BTWvcWf0AK',
                    'civil_id' => NULL,
                    'residency_number' => '1234567891',
                    'is_active' => 1,
                    'birthdate' => '1995-01-01',
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-28 13:34:29',
                    'updated_at' => '2024-04-29 13:15:25',
                ),
            6 =>
                array (
                    'id' => 31,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test_admin058',
                    'email' => 'alb@gmail.com',
                    'phone' => '574182924',
                    'password' => '$2y$10$cTiUxctrmAN5n0mXLrTVqOG9/Cd4958EW0aW2v0n2nfU7QzDD69ae',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => '1995-01-01',
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-28 13:48:56',
                    'updated_at' => '2024-04-29 19:31:30',
                ),
            7 =>
                array (
                    'id' => 32,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test_admin054',
                    'email' => 'test_admin054@gmail.com',
                    'phone' => '571741734',
                    'password' => '$2y$10$/GKsxFdIt83qTTajlw5ULugL/vBVePWacWvbjZIM2QcwdP3jKcmNG',
                    'civil_id' => '1234567891',
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-28 13:53:35',
                    'updated_at' => '2024-04-29 19:48:03',
                ),
            8 =>
                array (
                    'id' => 33,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test_admin0bjj',
                    'email' => 'vbkdvkdv@gmail.com',
                    'phone' => '574174789',
                    'password' => '$2y$10$qxTSG9RLtWU3zUPH9N9W2ejzT/JeuSf0N5rdqvFeJXAuYe.kC1HcK',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 0,
                    'birthdate' => '1995-01-01',
                    'verified_at' => '2024-04-28 13:56:36',
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-28 13:55:13',
                    'updated_at' => '2024-04-29 19:31:10',
                ),
            9 =>
                array (
                    'id' => 34,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test1',
                    'email' => 'test1@gmail.com',
                    'phone' => '575007500',
                    'password' => '$2y$10$gJ2BnP0TlwJoIBsJsRreQ.JN.qiSaJ4vep.rSII51nbIeKfIPaNSC',
                    'civil_id' => '1234567891',
                    'residency_number' => NULL,
                    'is_active' => 0,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-29 06:31:27',
                    'updated_at' => '2024-04-29 19:28:16',
                ),
            10 =>
                array (
                    'id' => 35,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'تست',
                    'email' => 'testadmin123@gmail.com',
                    'phone' => '540005000',
                    'password' => '$2y$10$sjxi9q4pvNNw0w86V/3OyucYQwNhRSwqZR1VO5tnM7sCi8XzeDB7i',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => '1995-01-01',
                    'verified_at' => '2024-04-29 07:08:56',
                    'remember_token' => NULL,
                    'deleted_at' => '2024-04-29 13:43:00',
                    'created_at' => '2024-04-29 07:07:50',
                    'updated_at' => '2024-04-29 13:43:00',
                ),
            11 =>
                array (
                    'id' => 36,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test22',
                    'email' => 'test22@gmail.com',
                    'phone' => '512341234',
                    'password' => '$2y$10$hKtWyHOc2wtlM6F4Zi9TXOwohVQqWXDPqoBz8SV5B/SQXMrU8BB4m',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => '2024-04-29 13:41:26',
                    'created_at' => '2024-04-29 08:44:03',
                    'updated_at' => '2024-04-29 13:41:26',
                ),
            12 =>
                array (
                    'id' => 37,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test222',
                    'email' => 'test222@gmail.com',
                    'phone' => '512341235',
                    'password' => '$2y$10$5jwiOSfgWTWbeUn7g6fg2eN8vPuNmEy6WXws1Hb3MT1shlGt.x4EC',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => '2024-04-29 08:47:26',
                    'remember_token' => NULL,
                    'deleted_at' => '2024-04-29 13:39:19',
                    'created_at' => '2024-04-29 08:46:10',
                    'updated_at' => '2024-04-29 13:39:19',
                ),
            13 =>
                array (
                    'id' => 38,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test222',
                    'email' => 'test2222@gmail.com',
                    'phone' => '512341236',
                    'password' => '$2y$10$/M1TaHH1yhagjVJi.FlJtuhRdrHOzbRNOxogBVKx./W36AeBHd9iC',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => '2024-04-29 13:39:29',
                    'created_at' => '2024-04-29 08:49:32',
                    'updated_at' => '2024-04-29 13:39:29',
                ),
            14 =>
                array (
                    'id' => 39,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'testtest',
                    'email' => 'testtest@gmail.com',
                    'phone' => '520003000',
                    'password' => '$2y$10$c2V5Dia.9GZivkH42n5rpOqyZBTyniBr5s3NJnMiwKliywbTsmAvu',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => '2024-04-29 13:39:15',
                    'created_at' => '2024-04-29 10:55:09',
                    'updated_at' => '2024-04-29 13:39:15',
                ),
            15 =>
                array (
                    'id' => 40,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'testadmin2',
                    'email' => 'testadmin2@gmail.com',
                    'phone' => '520008000',
                    'password' => '$2y$10$nhGRUQcW9cjeWxTd4fvNU.X0u5H8EQpLADUjbYsgEegiuc.HznXBe',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => '2024-04-29 11:13:31',
                    'remember_token' => NULL,
                    'deleted_at' => '2024-04-29 13:39:11',
                    'created_at' => '2024-04-29 11:12:51',
                    'updated_at' => '2024-04-29 13:39:11',
                ),
            16 =>
                array (
                    'id' => 41,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'testadmin10',
                    'email' => 'testadmin10@gmail.com',
                    'phone' => '570009000',
                    'password' => '$2y$10$03PmrTySqRUD7oWyV8Tta.oWWqzggCzGbVT2A1dGEfRxgdyeXlbpi',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 0,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => '2024-04-29 13:39:06',
                    'created_at' => '2024-04-29 11:14:28',
                    'updated_at' => '2024-04-29 13:39:06',
                ),
            17 =>
                array (
                    'id' => 42,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'testadmin10',
                    'email' => 'testadmin110@gmail.com',
                    'phone' => '560002000',
                    'password' => '$2y$10$UAYC/ZGjgHJadYKm5G6Osu8KAprVbDF6eNeDp23JF0L.wD.ZMd1oi',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => '2024-04-29 13:39:02',
                    'created_at' => '2024-04-29 11:20:14',
                    'updated_at' => '2024-04-29 13:39:02',
                ),
            18 =>
                array (
                    'id' => 43,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'eslam mohamed zaki',
                    'email' => 'eslamzaki973@gmail.com',
                    'phone' => '512346666',
                    'password' => '$2y$10$sxiCtQnGiLNL9g87uay3KO7i1uRW8hXdiCIcMCAmjhklTv9WSfki.',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 0,
                    'birthdate' => NULL,
                    'verified_at' => '2024-04-29 14:28:58',
                    'remember_token' => NULL,
                    'deleted_at' => '2024-04-29 19:26:49',
                    'created_at' => '2024-04-29 14:28:12',
                    'updated_at' => '2024-04-29 19:26:49',
                ),
            19 =>
                array (
                    'id' => 44,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test77',
                    'email' => 'test77@gmail.com',
                    'phone' => '500001000',
                    'password' => '$2y$10$Ol3TmCOxZw1kMWeFOwAjCekwP0lgh.qf2DG.SOfqZFnBBFe60nx3u',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => '2024-04-30 06:28:42',
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 06:28:21',
                    'updated_at' => '2024-04-30 06:28:42',
                ),
            20 =>
                array (
                    'id' => 45,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'admintest',
                    'email' => 'admintest@gmail.com',
                    'phone' => '540003000',
                    'password' => '$2y$10$KpcLy7e7/9hvHZqyXSeHveIx.NBlc6yloNEwiNIafDrZugvnh4Svi',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => '2024-04-30 06:41:10',
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 06:40:52',
                    'updated_at' => '2024-04-30 06:41:10',
                ),
            21 =>
                array (
                    'id' => 46,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'hesham',
                    'email' => 'muh.zed98@gmail.com',
                    'phone' => '555555556',
                    'password' => '$2y$10$tP229xq56jZE5Ix5cYor/e/S/reh.gOWr1Eze4SwbTRPSBMVgjpsK',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 07:47:25',
                    'updated_at' => '2024-04-30 07:47:25',
                ),
            22 =>
                array (
                    'id' => 47,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'testadmin2525',
                    'email' => 'testadmin55222@gmail.com',
                    'phone' => '540008000',
                    'password' => '$2y$10$t8eIHIzYUNjrrsgjjSNbJuPgW796r8bulSeVFtE6lzZNgLdO3feDm',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 07:49:04',
                    'updated_at' => '2024-04-30 07:49:04',
                ),
            23 =>
                array (
                    'id' => 48,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'heshamheder',
                    'email' => 'mfo@gmail.com',
                    'phone' => '512345666',
                    'password' => '$2y$10$2TcxyFdtn678MI48LDGm6.qXmcva7c/CHiR5TJUsT6UwA85hEBVYy',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => '2024-04-30 07:50:01',
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 07:49:53',
                    'updated_at' => '2024-04-30 07:50:01',
                ),
            24 =>
                array (
                    'id' => 49,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'eslam mohamed zaki',
                    'email' => 'ejoajsokapsd@gmail.com',
                    'phone' => '512345673',
                    'password' => '$2y$10$.RAxW0Zr7gKTMZhxzshcNO/XzCKC8.9NbIMm1HjjeaJwjEVKjRoLC',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 08:00:56',
                    'updated_at' => '2024-04-30 08:00:56',
                ),
            25 =>
                array (
                    'id' => 50,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'eslam mohamed zaki',
                    'email' => 'esasmdapm@gmail.com',
                    'phone' => '512345677',
                    'password' => '$2y$10$QttrKZPmfYTFinwahYWOnOBGESyiDus3MROCdUipE7gUgnnyyuhNK',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => '2024-04-30 08:08:38',
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 08:08:02',
                    'updated_at' => '2024-04-30 08:08:38',
                ),
            26 =>
                array (
                    'id' => 51,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'heshamh',
                    'email' => 'hesham@gmail.com',
                    'phone' => '512312312',
                    'password' => '$2y$10$VenImtYTvG2xkHZHLepp/.1OFeiK..ziFSihXk.a/T/NOvNjaEvwy',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 08:08:09',
                    'updated_at' => '2024-04-30 08:08:09',
                ),
            27 =>
                array (
                    'id' => 52,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'eslam  zaki',
                    'email' => 'eskskskkk@gmail.com',
                    'phone' => '512345674',
                    'password' => '$2y$10$n.eaOzdVA8UV1Pv7bNWxA.q0wr2YV8HPBQVhbYbn/BGH1nLCR28uK',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => '2024-04-30 08:28:11',
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 08:27:18',
                    'updated_at' => '2024-04-30 08:28:11',
                ),
            28 =>
                array (
                    'id' => 53,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'test_admin01',
                    'email' => 'test_admin0u1@gmail.com',
                    'phone' => '540003500',
                    'password' => '$2y$10$aArijcQA1lgj5on2jsQSPesaGTzoM4nhbiIR/qt9a0UPQ4SkZDxcy',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => NULL,
                    'remember_token' => NULL,
                    'deleted_at' => NULL,
                    'created_at' => '2024-04-30 08:42:28',
                    'updated_at' => '2024-05-01 09:57:51',
                ),
            29 =>
                array (
                    'id' => 54,
                    'type' => UserTypeEnum::user->value,
                    'name' => 'testadmin22',
                    'email' => 'testadmin0022@gmail.com',
                    'phone' => '575004500',
                    'password' => '$2y$10$oQ.2ESz6Hxo3dwBYy/./p.8/CNLAmg8atNtux850qOa2eG2J5sCEq',
                    'civil_id' => NULL,
                    'residency_number' => NULL,
                    'is_active' => 1,
                    'birthdate' => NULL,
                    'verified_at' => '2024-05-01 06:11:45',
                    'remember_token' => NULL,
                    'deleted_at' => '2024-05-01 08:09:53',
                    'created_at' => '2024-05-01 06:11:29',
                    'updated_at' => '2024-05-01 08:09:53',
                ),
        ));
    }
}
